### ISSUE TITLE
Get data of calendar

### ISSUE THREAD

**Issue by fercreek** [gabrielhpugliese/meteor_supercalendar#10]
How I can get the data of an event(days), and insert in an object? 
I'm using SuperCalendar.events.onEventClick but i don't know how to do that.

**Comment by gabrielhpugliese** [comment]
It's the same API as fullcalendar: http://fullcalendar.io/docs/mouse/eventClick/

```
SuperCalendar.events.onEventClick = function(calEvent, jsEvent, view) {
// use calEvent here
};
```

**Comment by fercreek** [comment]
Thanks :D
