### ISSUE TITLE
Add hour time events

### ISSUE THREAD

**Issue by divyakkm** [gabrielhpugliese/meteor_supercalendar#6]
This is the desired action. If I click at 5pm, it should open a modal to create an event at 5pm-6pm(end time customizable) and add the event details like in Google calendar. It will be great if you can help me with this. Or recommend some other ways of accomplishing this in Meteor. Thanks!

**Comment by gabrielhpugliese** [comment]
Do you mean on the other visualization modes?

**Comment by divyakkm** [comment]
Yes, in the week and weekday mode. The ability to create time specific events. 

And also display its details. I noticed tht if something has time, then you cannot see it's title and description. But for a day event you can see its details.

**Comment by gabrielhpugliese** [comment]
I get it. Thanks for feedback. Gonna work on it.

**Comment by divyakkm** [comment]
Great, thanks! I would be happy to help if needed. Great work with the package. I hope I can use it for my project. Thanks again.

**Comment by gabrielhpugliese** [comment]
If your project is open to internet, send the url so I can link it in Readme

**Comment by gabrielhpugliese** [comment]
If you use tbe calendar, of course ;)

**Comment by gabrielhpugliese** [comment]
@divyakkm, can you teste, please?
https://github.com/gabrielhpugliese/meteor_supercalendar/releases/tag/v0.7.0

**Comment by gabrielhpugliese** [comment]
Hmmm just a note: I forgot the end time :(

**Comment by gabrielhpugliese** [comment]
I've created another issue to add end time: https://github.com/gabrielhpugliese/meteor_supercalendar/issues/7

**Comment by gabrielhpugliese** [comment]
Gonna close this one
