### ISSUE TITLE
Time field does not appear in new event modal after selecting "I know the time"

### ISSUE THREAD

**Issue by rayrrr** [gabrielhpugliese/meteor_supercalendar#9]
I click to create a new event in the default (month) view. I select the "I know the time" radio button, but the time field does not appear. I cannot select a time for my event.

I am experiencing this bug on both my localhost:3000 server and [supercalendar.meteor.com](supercalendar.meteor.com).

![screen shot 2015-05-03 at 1 06 51 pm](https://cloud.githubusercontent.com/assets/7869818/7445959/7e817f68-f195-11e4-8357-18267b888f27.png)

**Comment by gabrielhpugliese** [comment]
Gonna fix that today, thanks

**Comment by gabrielhpugliese** [comment]
Fixed: https://github.com/gabrielhpugliese/meteor_supercalendar/releases/tag/v0.7.1
